
erDiagram
    City ||--o{ User : cities
    User ||--|{ City : users
    
    User {
        int id
        string name
        string email
        string password
        list cities
    }
    City {
        int id
        string name
        list users

    }
